// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pendu.Persistence.Data
{
    using Pendu.Common.Entities;

    public class PenduDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<PenduDbContext>
    {
        public PenduDbContext Create()
        {
            return new PenduDbContext();
        }
    }
}
// </auto-generated>
