// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pendu.Persistence.Data
{
    using Pendu.Common.Entities;

    // PenduUserLogins
    public class PenduUserLogin
    {
        public string LoginProvider { get; set; } // LoginProvider (Primary key) (length: 128)
        public string ProviderKey { get; set; } // ProviderKey (Primary key) (length: 128)
        public string UserId { get; set; } // UserId (Primary key) (length: 128)

        // Foreign keys

        /// <summary>
        /// Parent PenduUser pointed by [PenduUserLogins].([UserId]) (FK_dbo.PenduUserLogins_dbo.PenduUsers_UserId)
        /// </summary>
        public virtual PenduUser PenduUser { get; set; } // FK_dbo.PenduUserLogins_dbo.PenduUsers_UserId
    }

}
// </auto-generated>
