// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pendu.Entities.Models
{
    using Pendu.Common.Entities;
    
    // PenduRoles
    public class PenduRole: ModelBase
    {
        public string Id { get; set; } // Id (Primary key) (length: 128)
        public string Name { get; set; } // Name (length: 256)

        // Reverse navigation

        /// <summary>
        /// Child PenduUsers (Many-to-Many) mapped by table [PenduUserRoles]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PenduUser> PenduUsers { get; set; } // Many to many mapping

        public PenduRole()
        {
            PenduUsers = new System.Collections.Generic.List<PenduUser>();
        }
    }

}
// </auto-generated>
