// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pendu.Entities.Models
{
    using Pendu.Common.Entities;

    // PenduUsers
    public class PenduUser: ModelBase
    {
        public string Id { get; set; } // Id (Primary key) (length: 128)
        public string Email { get; set; } // Email (length: 256)
        public bool EmailConfirmed { get; set; } // EmailConfirmed
        public string PasswordHash { get; set; } // PasswordHash
        public string SecurityStamp { get; set; } // SecurityStamp
        public string PhoneNumber { get; set; } // PhoneNumber
        public bool PhoneNumberConfirmed { get; set; } // PhoneNumberConfirmed
        public bool TwoFactorEnabled { get; set; } // TwoFactorEnabled
        public System.DateTime? LockoutEndDateUtc { get; set; } // LockoutEndDateUtc
        public bool LockoutEnabled { get; set; } // LockoutEnabled
        public int AccessFailedCount { get; set; } // AccessFailedCount
        public string UserName { get; set; } // UserName (length: 256)

        // Reverse navigation

        /// <summary>
        /// Child PenduRoles (Many-to-Many) mapped by table [PenduUserRoles]
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PenduRole> PenduRoles { get; set; } // Many to many mapping
        /// <summary>
        /// Child PenduUserClaims where [PenduUserClaims].[UserId] point to this entity (FK_dbo.PenduUserClaims_dbo.PenduUsers_UserId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PenduUserClaim> PenduUserClaims { get; set; } // PenduUserClaims.FK_dbo.PenduUserClaims_dbo.PenduUsers_UserId
        /// <summary>
        /// Child PenduUserLogins where [PenduUserLogins].[UserId] point to this entity (FK_dbo.PenduUserLogins_dbo.PenduUsers_UserId)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PenduUserLogin> PenduUserLogins { get; set; } // PenduUserLogins.FK_dbo.PenduUserLogins_dbo.PenduUsers_UserId

        public PenduUser()
        {
            PenduUserClaims = new System.Collections.Generic.List<PenduUserClaim>();
            PenduUserLogins = new System.Collections.Generic.List<PenduUserLogin>();
            PenduRoles = new System.Collections.Generic.List<PenduRole>();
        }
    }

}
// </auto-generated>
